name = persian_chat_fix
title = Persian Chat Fix
description = Fixes Persian & Arabic chat with proper letter shaping and RTL support. Requires a font that supports Persian/Arabic characters.
version = 1.1.1
author = Artin N.m
license = MIT
media_license = MIT